-- DROP TABLE apps_portfolio, apps_service, apps_skills,apps_statistic,apps_user,auth_group,auth_group_permissions,auth_permission,auth_user,auth_user_groups,auth_user_user_permissions,django_admin_log,django_content_type,django_migrations,django_session;

