# Generated by Django 5.0.6 on 2024-07-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password1',
            field=models.CharField(default='1', max_length=150, verbose_name='parol'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='password2',
            field=models.CharField(default='1', max_length=150, verbose_name='takror parol'),
            preserve_default=False,
        ),
    ]
